name: Trigger CircleCI

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - master
      - 'JAHIA-[0-9]-[0-9]-[0-9]-X-BRANCH'

jobs:
  trigger_circle_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI pipeline
        env:
          # to get access to secrets.CIRCLECI_PIPELINE_LAUNCH_TOKEN, provide GITHUB_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: curl -X POST --url 'https://circleci.com/api/v2/project/gh/${{ github.repository }}/pipeline'
          --header 'circle-token:${{ secrets.CIRCLECI_PIPELINE_LAUNCH_TOKEN }}'
          --header 'content-type:application/json'
          --data '{ "branch":"${{ github.HEAD_REF }}", "parameters":{ "run_pull_request":true, "target_branch":"${{ github.BASE_REF }}", "pull_request_number":"${{ github.event.number }}", "github_repository":"${{ github.repository }}" } }'
